Upgrade Basenine version from `0.2.26` to `0.3.0`
up9inc/mizu pull request #614
Opened 2022-01-10 09:39 UTC by mertyildiran

2022-01-10 15:08 UTC, nimrod-up9 requested changes

2022-01-10 15:08 UTC, nimrod-up9 commented on ui/src/components/EntryListItem/EntryListItem.tsx
> +    console.log("entry:", entry);
Left over from a debug session?

2022-01-11 03:19 UTC, mertyildiran commented on ui/src/components/EntryListItem/EntryListItem.tsx
> +    console.log("entry:", entry);
@nimrod-up9 oops, I'm sorry. Removed with https://github.com/up9inc/mizu/commit/df774c801e5074bb7847d7dbd915904d08ed41a1

2022-01-11 09:51 UTC, nimrod-up9 approved these changes

2022-01-11 09:51 UTC, merged