unhide svcmap + CHANGELOG
up9inc/mizu pull request #724
Opened 2022-01-30 20:08 UTC by haiut

2022-01-30 20:43 UTC, IgorGov commented on cli/config/configStruct.go
> +	ServiceMap             bool                        `yaml:"service-map" default:"false" readonly:""`
To unhide you need to remove the readonly

2022-01-31 07:34 UTC, IgorGov commented on cli/config/configStruct.go
> +	ServiceMap             bool                        `yaml:"service-map" default:"false" readonly:""`
```suggestion
	ServiceMap             bool                        `yaml:"service-map" default:"false"`
```

2022-01-31 08:44 UTC, RoyUP9 approved these changes

2022-01-31 08:46 UTC, RoyUP9 commented on docs/CHANGELOG.md
> +* in Mizu GUI the filter query can now applied by pressing ENTER
CONTROL + ENTER

2022-01-31 08:47 UTC, RoyUP9 requested changes
small fix

2022-01-31 15:04 UTC, RoyUP9 approved these changes

2022-01-31 15:20 UTC, merged